// AUTO-GENERATED by migration/optimize-service-art.mjs — do not edit by hand.
// Service slugs that have an optimized raster thumbnail in public/services-art/<slug>.webp.
export const RASTER_SERVICE_ART = new Set<string>([
]);

export function serviceArt(slug: string): string {
  return RASTER_SERVICE_ART.has(slug)
    ? `/services-art/${slug}.webp`
    : `/services-art/${slug}.svg`;
}
