"use client";
import { Canvas, useFrame, useLoader, useThree } from "@react-three/fiber";
import { Suspense, useEffect, useMemo, useRef, useState } from "react";
import * as THREE from "three";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";
import { MeshoptDecoder } from "three/examples/jsm/libs/meshopt_decoder.module.js";
import { RoomEnvironment } from "three/examples/jsm/environments/RoomEnvironment.js";

/**
 * Homepage hero: a glossy neural brain (public/models/neural-brain.glb,
 * generated by scripts/models/generate-brain.mjs) whose folds glow where the
 * selected service lives.
 *
 * The model's COLOR_0 carries meaning rather than paint: rgb are the Data /
 * Intelligence / Automation region masks and alpha is sulcus depth. Signals
 * flow from each service node into its region, and selecting a node shifts
 * the glow there.
 */

const MODEL_URL = "/models/neural-brain.glb";
/** One per hero card, in heroServices order. */
const NODE_COLORS = ["#3b6cf0", "#7c4dff", "#ff6a3d", "#ff8a3d", "#2bb3a0", "#6a4df5"];
const SIGNAL = new THREE.Color("#ff2414");
const EMBER = new THREE.Color("#ff9a3c");

/** Fallback node positions (scene space), used until the cards are measured. */
const NODES: [number, number, number][] = [
  [-1.75, 1.3, 0.6], // Data
  [-2.6, 0.05, 0.6], // AI / ML
  [1.3, 1.45, 0.6], // Intelligence
  [2.1, 0.0, 0.6], // Automation
  [1.55, -1.5, 0.6], // Data Analytics
  [-1.25, -1.6, 0.6], // LLMOps
];
/** Where each node's signal enters the brain (scene space). */
const REGION_ANCHORS: [number, number, number][] = [
  [-0.7, 0.8, 0.3],
  [-1.0, 0.0, 0.5],
  [0.45, 0.75, 0.8],
  [0.95, 0.05, 0.5],
  [0.6, -0.55, 0.6],
  [-0.4, -0.6, 0.6],
];
const CAMERA = { position: [0, 0.2, 7.8] as [number, number, number], fov: 43 };
const PARTICLES_PER_PATH = 14;
/** Depth of the plane the nodes sit on, just in front of the brain. */
const NODE_Z = 0.9;

/** Normalised device coordinates from the HTML cards: [x, y] in -1..1. */
export type NodeAnchors = [number, number][];
const DOTS_PER_PATH = 28;

// Per-frame mutable state lives at module scope: the hero mounts one scene,
// and the React compiler forbids mutating values created during render.
const uniforms = {
  uTime: { value: 0 },
  uRegion: { value: new THREE.Vector3(0, 1, 0) },
};
const regionTarget = new THREE.Vector3();
const scratchPoint = new THREE.Vector3();
const scratchColor = new THREE.Color();

function useNeuralMaterial() {
  return useMemo(() => {
    const material = new THREE.MeshPhysicalMaterial({
      color: "#eef2fa",
      roughness: 0.3,
      metalness: 0,
      clearcoat: 0.75,
      clearcoatRoughness: 0.22,
      sheen: 0.7,
      sheenRoughness: 0.45,
      sheenColor: new THREE.Color("#ffd6cc"),
      iridescence: 0.15,
      vertexColors: true,
    });
    material.onBeforeCompile = (shader) => {
      Object.assign(shader.uniforms, uniforms, {
        uSignal: { value: SIGNAL },
        uEmber: { value: EMBER },
      });
      shader.vertexShader = shader.vertexShader
        .replace(
          "#include <common>",
          "#include <common>\nvarying vec3 vNeuralPos;",
        )
        .replace(
          "#include <begin_vertex>",
          "#include <begin_vertex>\nvNeuralPos = (modelMatrix * vec4(transformed, 1.0)).xyz;",
        );
      shader.fragmentShader = shader.fragmentShader
        .replace(
          "#include <common>",
          `#include <common>
varying vec3 vNeuralPos;
uniform float uTime;
uniform vec3 uRegion;
uniform vec3 uSignal;
uniform vec3 uEmber;`,
        )
        // vColor is data, not albedo. The tissue gets a soft pastel wash
        // fixed in world space, so it reads like coloured studio light.
        .replace(
          "#include <color_fragment>",
          `float tintX = smoothstep(-2.2, 2.2, vNeuralPos.x);
float tintY = smoothstep(-2.0, 2.0, vNeuralPos.y);
vec3 tint = mix(mix(vec3(1.0, 0.72, 0.82), vec3(1.0, 0.82, 0.66), tintY), vec3(0.66, 0.78, 1.0), tintX);
diffuseColor.rgb *= mix(vec3(1.0), tint * tint, 0.75 + 0.25 * vColor.a);`,
        )
        .replace(
          "#include <emissivemap_fragment>",
          `#include <emissivemap_fragment>
float cavity = vColor.a;
float region = dot(vColor.rgb, uRegion);
// Two travelling fronts, so activity reads as signalling rather than a pulse.
float waveA = pow(0.5 + 0.5 * sin(dot(vNeuralPos, vec3(0.55, 0.8, 0.25)) * 7.0 - uTime * 2.1), 5.0);
float waveB = pow(0.5 + 0.5 * sin(dot(vNeuralPos, vec3(-0.7, 0.2, 0.68)) * 9.0 - uTime * 1.4), 7.0);
float activity = 0.4 + 0.6 * max(waveA, waveB);
// Deep folds only, and almost nothing outside the selected region.
float fold = smoothstep(0.45, 0.95, cavity);
float focus = smoothstep(0.15, 0.75, region);
float glow = fold * (0.03 + 1.6 * focus) * activity;
diffuseColor.rgb = mix(diffuseColor.rgb, vec3(0.95, 0.4, 0.45), fold * focus * 0.55);
// Kept below ~1.2 so ACES tone mapping does not bleach the red to white.
totalEmissiveRadiance += mix(uSignal, uEmber, waveB * 0.6) * glow * 0.55;`,
        );
    };
    return material;
  }, []);
}

/** A procedural studio for clearcoat reflections — nothing is downloaded. */
function applyEnvironment(gl: THREE.WebGLRenderer, scene: THREE.Scene) {
  const pmrem = new THREE.PMREMGenerator(gl);
  scene.environment = pmrem.fromScene(new RoomEnvironment(), 0.04).texture;
  scene.environmentIntensity = 0.55;
  pmrem.dispose();
}

function Brain({
  region,
  playing,
  onReady,
}: {
  region: number;
  playing: boolean;
  onReady?: () => void;
}) {
  const gltf = useLoader(GLTFLoader, MODEL_URL, (loader) => {
    loader.setMeshoptDecoder(MeshoptDecoder);
  });
  const material = useNeuralMaterial();
  const group = useRef<THREE.Group>(null);
  const halo = useRef<THREE.Mesh>(null);
  const time = useRef(0);

  const model = useMemo(() => {
    const root = gltf.scene.clone(true);
    root.traverse((o) => {
      if ((o as THREE.Mesh).isMesh) (o as THREE.Mesh).material = material;
    });
    return root;
  }, [gltf, material]);

  useEffect(() => {
    onReady?.();
    return () => material.dispose();
  }, [material, onReady]);

  useFrame((state, delta) => {
    if (playing) time.current += Math.min(delta, 0.05);
    const t = time.current;
    uniforms.uTime.value = t;
    regionTarget.set(region === 0 ? 1 : 0, region === 1 ? 1 : 0, region === 2 ? 1 : 0);
    uniforms.uRegion.value.lerp(regionTarget, 0.05);
    if (group.current) {
      // A gentle sway, not a spin: the recognisable three-quarter view stays.
      group.current.rotation.y = -0.55 + Math.sin(t * 0.18) * 0.35 + state.pointer.x * 0.18;
      group.current.rotation.x = 0.12 - state.pointer.y * 0.1;
      group.current.position.y = 0.15 + Math.sin(t * 0.6) * 0.05;
    }
    if (halo.current) {
      const m = halo.current.material as THREE.ShaderMaterial;
      m.uniforms.uTime.value = t;
    }
  });

  return (
    <>
      <mesh ref={halo} position={[0, -0.1, -1.4]} renderOrder={-1}>
        <planeGeometry args={[7, 7]} />
        <shaderMaterial
          transparent
          depthWrite={false}
          blending={THREE.AdditiveBlending}
          uniforms={{ uTime: { value: 0 }, uColor: { value: SIGNAL } }}
          vertexShader={`varying vec2 vUv; void main(){ vUv = uv; gl_Position = projectionMatrix * modelViewMatrix * vec4(position,1.0); }`}
          fragmentShader={`varying vec2 vUv; uniform float uTime; uniform vec3 uColor;
            void main(){ float d = length(vUv - 0.5) * 2.0;
              float g = pow(max(0.0, 1.0 - d), 2.6) * (0.3 + 0.06 * sin(uTime * 1.3));
              gl_FragColor = vec4(uColor * g, g); }`}
        />
      </mesh>
      <group ref={group} scale={2.15} position={[0.1, 0.15, 0]}>
        <primitive object={model} />
      </group>
    </>
  );
}

function Signals({
  selected,
  onSelect,
  playing,
  anchors,
}: {
  selected: number;
  onSelect: (i: number) => void;
  playing: boolean;
  anchors?: NodeAnchors;
}) {
  const particles = useRef<THREE.Points>(null);
  const time = useRef(0);
  const aspect = useThree((s) => s.size.width / s.size.height);
  // Project each card's brain-facing edge onto the node plane, so every card
  // gets its own sphere wherever the layout puts it.
  const nodes = useMemo(() => {
    if (!anchors || anchors.length !== NODES.length) return NODES;
    // A private copy of the scene camera, so the shared one is never mutated.
    const camera = new THREE.PerspectiveCamera(CAMERA.fov, aspect, 0.1, 100);
    camera.position.set(...CAMERA.position);
    camera.lookAt(0, 0, 0); // R3F aims its default camera at the origin too
    camera.updateMatrixWorld();
    return anchors.map(([x, y]) => {
      const ray = new THREE.Vector3(x, y, 0.5).unproject(camera).sub(camera.position).normalize();
      const t = (NODE_Z - camera.position.z) / ray.z;
      return camera.position.clone().addScaledVector(ray, t).toArray() as [number, number, number];
    });
  }, [anchors, aspect]);
  const { curves, lines, positions, colors } = useMemo(() => {
    const curves = nodes.map((n, i) => {
      const start = new THREE.Vector3(...n);
      const end = new THREE.Vector3(...REGION_ANCHORS[i]);
      const bend = start.x < 0 ? -0.35 : 0.35;
      const mid = start.clone().lerp(end, 0.5).add(new THREE.Vector3(bend, 0.25, 0.9));
      return new THREE.QuadraticBezierCurve3(start, mid, end);
    });
    const lines = curves.map(
      (c) => new Float32Array(c.getSpacedPoints(DOTS_PER_PATH).flatMap((p) => p.toArray())),
    );
    const count = curves.length * PARTICLES_PER_PATH;
    return {
      curves,
      lines,
      positions: new Float32Array(count * 3),
      colors: new Float32Array(count * 3),
    };
  }, [nodes]);

  useFrame((_, delta) => {
    if (playing) time.current += Math.min(delta, 0.05);
    const pts = particles.current;
    if (!pts) return;
    const pos = pts.geometry.attributes.position as THREE.BufferAttribute;
    const col = pts.geometry.attributes.color as THREE.BufferAttribute;
    for (let c = 0; c < curves.length; c++) {
      const active = c === selected;
      for (let i = 0; i < PARTICLES_PER_PATH; i++) {
        const k = c * PARTICLES_PER_PATH + i;
        // flow from node → brain; the selected path runs faster and brighter
        const u = (i / PARTICLES_PER_PATH + time.current * (active ? 0.16 : 0.07)) % 1;
        curves[c].getPoint(u, scratchPoint);
        pos.setXYZ(k, scratchPoint.x, scratchPoint.y, scratchPoint.z);
        const fade = Math.sin(u * Math.PI);
        scratchColor.set(NODE_COLORS[c]).multiplyScalar((active ? 1.3 : 0.5) * fade);
        col.setXYZ(k, scratchColor.r, scratchColor.g, scratchColor.b);
      }
    }
    pos.needsUpdate = true;
    col.needsUpdate = true;
  });

  return (
    <>
      {lines.map((array, i) => (
        <points key={i}>
          <bufferGeometry>
            <bufferAttribute attach="attributes-position" args={[array, 3]} />
          </bufferGeometry>
          <pointsMaterial
            color={NODE_COLORS[i]}
            size={0.035}
            transparent
            opacity={i === selected ? 0.95 : 0.45}
            depthWrite={false}
          />
        </points>
      ))}
      <points ref={particles}>
        <bufferGeometry>
          <bufferAttribute attach="attributes-position" args={[positions, 3]} />
          <bufferAttribute attach="attributes-color" args={[colors, 3]} />
        </bufferGeometry>
        <pointsMaterial
          size={0.06}
          vertexColors
          transparent
          depthWrite={false}
          blending={THREE.AdditiveBlending}
          sizeAttenuation
        />
      </points>
      {nodes.map((position, i) => (
        <group key={i} position={position}>
          <mesh
            onClick={(e) => {
              e.stopPropagation();
              onSelect(i);
            }}
          >
            <sphereGeometry args={[selected === i ? 0.14 : 0.115, 32, 24]} />
            <meshPhysicalMaterial
              color={NODE_COLORS[i]}
              emissive={NODE_COLORS[i]}
              emissiveIntensity={selected === i ? 0.6 : 0.25}
              roughness={0.18}
              clearcoat={1}
              clearcoatRoughness={0.1}
            />
          </mesh>
          {/* glass ring, so each node reads as a lit bead in a socket */}
          <mesh>
            <torusGeometry args={[selected === i ? 0.21 : 0.18, 0.012, 12, 48]} />
            <meshPhysicalMaterial
              color="#ffffff"
              emissive={NODE_COLORS[i]}
              emissiveIntensity={selected === i ? 0.35 : 0.1}
              transparent
              opacity={selected === i ? 0.9 : 0.55}
              roughness={0.15}
              clearcoat={1}
            />
          </mesh>
        </group>
      ))}
      {/* orbit ring around the brain */}
      <mesh rotation={[1.25, 0.2, -0.35]}>
        <torusGeometry args={[2.75, 0.008, 8, 160]} />
        <meshBasicMaterial color="#9fb3cf" transparent opacity={0.5} />
      </mesh>
    </>
  );
}

function supportsWebGL2() {
  try {
    const canvas = document.createElement("canvas");
    const gl = canvas.getContext("webgl2");
    gl?.getExtension("WEBGL_lose_context")?.loseContext();
    return !!gl;
  } catch {
    return false;
  }
}

export default function NeuralScene(props: {
  selected: number;
  region: number;
  onSelect: (i: number) => void;
  playing: boolean;
  onReady?: () => void;
  anchors?: NodeAnchors;
}) {
  const [supported, setSupported] = useState(supportsWebGL2);
  if (!supported) return null;
  return (
    <Canvas
      camera={CAMERA}
      dpr={[1, 1.5]}
      frameloop={props.playing ? "always" : "demand"}
      gl={{ antialias: true, alpha: true, powerPreference: "high-performance" }}
      onCreated={({ gl, scene }) => {
        applyEnvironment(gl, scene);
        gl.domElement.addEventListener(
          "webglcontextlost",
          () => setSupported(false),
          { once: true },
        );
      }}
    >
      <ambientLight intensity={0.35} />
      <hemisphereLight args={["#ffffff", "#9db0cc", 0.8]} />
      <directionalLight position={[-3, 5, 5]} intensity={2} />
      {/* warm rim from behind, like light through tissue */}
      <directionalLight position={[2.5, -1.5, -4]} intensity={2.2} color="#ff9a82" />
      <Suspense fallback={null}>
        <Brain region={props.region} playing={props.playing} onReady={props.onReady} />
      </Suspense>
      <Signals
        selected={props.selected}
        onSelect={props.onSelect}
        playing={props.playing}
        anchors={props.anchors}
      />
    </Canvas>
  );
}
